/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gloskampen.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JWindow;
import javax.swing.SwingConstants;

 
/**
 * Latest update: 2014-01-07 22:44
 * @author Fredrik Johansson 
 */
public class MainView extends javax.swing.JFrame 
{
    private ButtonGroup groupSelectOrType;
    private final Dimension screenSize;
    private BufferedImage bgImg; 
    private final ButtonStyle btnStyle;
    private final ArrayList<JPanel> allPanels;
    private final int splashDelayInSeconds = 3;
         
    
    /**
     * Creates new form MainView
     */
    public MainView() 
    {      
        this.setResizable(false); // prevent window resizing
        
        // style the window borders a bit
        this.setUndecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.WARNING_DIALOG);
        
        // load background image
        try 
        {
            bgImg = ImageIO.read(new File("images/bgImg3.jpg"));
        } 
        catch(IOException e) 
        {
        }
        
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();         
        displaySplashScreen();        
        initComponents();                  
        this.setLocation(screenSize.width / 2 - this.getSize().width / 2, screenSize.height / 2 - this.getSize().height / 2); 
        createGroupSelectOrType();                   
        allPanels = new ArrayList<>(); 
        
        // add panels to the panel ArrayList
        allPanels.add(panelMainMenu);
        allPanels.add(panelLangDiffSelect);
        allPanels.add(panelPreGame);
        allPanels.add(panelGame);
        allPanels.add(panelSettings);
        allPanels.add(panelHelp);
        allPanels.add(panelHighscore);
        allPanels.add(panelAddWord);
        allPanels.add(panelListWords);
        
        // create new ButtonStyle object to style all buttons
        btnStyle = new ButtonStyle(allPanels);           
    }    
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMainMenu = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        }
        ;
        labelLogo = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnHighScore = new javax.swing.JButton();
        btnAddWord = new javax.swing.JButton();
        btnListWords = new javax.swing.JButton();
        labelSettingsIcon = new javax.swing.JLabel();
        labelHelpIcon = new javax.swing.JLabel();
        panelLangDiffSelect = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelCBFrom1 = new javax.swing.JLabel();
        comBoxFrom1 = new javax.swing.JComboBox();
        labelCBTo1 = new javax.swing.JLabel();
        comBoxTo1 = new javax.swing.JComboBox();
        labelCBDiff = new javax.swing.JLabel();
        comBoxDiff = new javax.swing.JComboBox();
        labelRBSelectType = new javax.swing.JLabel();
        radBtnSelectChoices = new javax.swing.JRadioButton();
        radBtnTypeWord = new javax.swing.JRadioButton();
        btnConfirmLangDiff = new javax.swing.JButton();
        btnLangDiffSelectBack = new javax.swing.JButton();
        labelChBThreeChoices = new javax.swing.JLabel();
        chBoxThreeChoicesYes = new javax.swing.JCheckBox();
        panelPreGame = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnStartGame = new javax.swing.JButton();
        labelPreGame1 = new javax.swing.JLabel();
        labelPreGame2 = new javax.swing.JLabel();
        labelPreGame3 = new javax.swing.JLabel();
        labelPreGame4 = new javax.swing.JLabel();
        labelPreGameFrom = new javax.swing.JLabel();
        labelPreGameTo = new javax.swing.JLabel();
        labelPreGame5 = new javax.swing.JLabel();
        labelPreGameDiff = new javax.swing.JLabel();
        labelPreGame6 = new javax.swing.JLabel();
        labelPreGameSelectType = new javax.swing.JLabel();
        btnPreGameBack = new javax.swing.JButton();
        panelGame = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnNext = new javax.swing.JButton();
        txtFldAnswer = new javax.swing.JTextField();
        labelWordToTranslate = new javax.swing.JLabel();
        labelWordNo = new javax.swing.JLabel();
        labelEndGame = new javax.swing.JLabel();
        btnEndGame = new javax.swing.JButton();
        panelGameTest = new javax.swing.JPanel();
        panelGameTest2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comBoxThreeWords = new javax.swing.JComboBox();
        labelCBThreeWords = new javax.swing.JLabel();
        scrPaneFeedback2 = new javax.swing.JScrollPane();
        scrPaneFeedback1 = new javax.swing.JScrollPane();
        labelFeedback = new javax.swing.JTextArea();
        panelSettings = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnSettingsBack = new javax.swing.JButton();
        labelSettings = new javax.swing.JLabel();
        panelHelp = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnHelpBack = new javax.swing.JButton();
        labelHelp = new javax.swing.JLabel();
        panelHighscore = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnHighscoreBack = new javax.swing.JButton();
        scrPaneHighscore = new javax.swing.JScrollPane();
        txtPaneHighscore = new javax.swing.JTextPane();
        labelHighscore = new javax.swing.JLabel();
        panelAddWord = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnAddWordBack = new javax.swing.JButton();
        labelCBFrom2 = new javax.swing.JLabel();
        txtFldAddWordFrom = new javax.swing.JTextField();
        comBoxFrom2 = new javax.swing.JComboBox();
        labelAddWordFromError = new javax.swing.JLabel();
        labelCBTo2 = new javax.swing.JLabel();
        comBoxTo2 = new javax.swing.JComboBox();
        txtFldAddWordTo = new javax.swing.JTextField();
        labelAddWordToError = new javax.swing.JLabel();
        txtFldAddWordNewLang = new javax.swing.JTextField();
        btnAddWordAdd = new javax.swing.JButton();
        btnAddWordClear = new javax.swing.JButton();
        labelSubmitNewLang = new javax.swing.JLabel();
        btnNewLangSave = new javax.swing.JButton();
        labelHighscore1 = new javax.swing.JLabel();
        panelListWords = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnListWordsBack = new javax.swing.JButton();
        scrPaneListWords = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        labelCBFrom3 = new javax.swing.JLabel();
        comBoxFrom3 = new javax.swing.JComboBox();
        labelCBTo3 = new javax.swing.JLabel();
        comBoxTo3 = new javax.swing.JComboBox();
        btnListWordsSave = new javax.swing.JButton();
        btnListWordsShow = new javax.swing.JButton();
        labelHighscore2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gloskampen");
        getContentPane().setLayout(new java.awt.CardLayout());

        panelMainMenu.setPreferredSize(new java.awt.Dimension(960, 750));

        labelLogo.setFont(new java.awt.Font("Stencil Std", 1, 31)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(154, 111, 77));
        labelLogo.setText("GLOSKAMPEN");

        btnNewGame.setFont(new java.awt.Font("Californian FB", 1, 17)); // NOI18N
        btnNewGame.setText("Nytt spel");
        btnNewGame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewGame.setFocusPainted(false);
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnHighScore.setFont(new java.awt.Font("Californian FB", 1, 17)); // NOI18N
        btnHighScore.setText("Topplista");
        btnHighScore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighScoreActionPerformed(evt);
            }
        });

        btnAddWord.setFont(new java.awt.Font("Californian FB", 1, 17)); // NOI18N
        btnAddWord.setText("Lägg till glosa");
        btnAddWord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordActionPerformed(evt);
            }
        });

        btnListWords.setFont(new java.awt.Font("Californian FB", 1, 17)); // NOI18N
        btnListWords.setText("Lista glosor");
        btnListWords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListWordsActionPerformed(evt);
            }
        });

        labelSettingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gloskampen/view/images/wrench2.png"))); // NOI18N
        labelSettingsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSettingsIconMouseClicked(evt);
            }
        });

        labelHelpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gloskampen/view/images/help6.png"))); // NOI18N
        labelHelpIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHelpIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMainMenuLayout = new javax.swing.GroupLayout(panelMainMenu);
        panelMainMenu.setLayout(panelMainMenuLayout);
        panelMainMenuLayout.setHorizontalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenuLayout.createSequentialGroup()
                .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainMenuLayout.createSequentialGroup()
                        .addContainerGap(394, Short.MAX_VALUE)
                        .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnListWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddWord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHighScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNewGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMainMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelSettingsIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpIcon))
                    .addGroup(panelMainMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        panelMainMenuLayout.setVerticalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHelpIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSettingsIcon))
                .addGap(71, 71, 71)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHighScore, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        getContentPane().add(panelMainMenu, "card2");

        labelCBFrom1.setBackground(new java.awt.Color(106, 78, 57));
        labelCBFrom1.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelCBFrom1.setForeground(new java.awt.Color(255, 255, 255));
        labelCBFrom1.setText("Välj från-språk:");
        labelCBFrom1.setOpaque(true);

        comBoxFrom1.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        comBoxFrom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Svenska", "Engelska" }));
        comBoxFrom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxFrom1ActionPerformed(evt);
            }
        });

        labelCBTo1.setBackground(new java.awt.Color(106, 78, 57));
        labelCBTo1.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelCBTo1.setForeground(new java.awt.Color(255, 255, 255));
        labelCBTo1.setText("Välj till-språk:");
        labelCBTo1.setOpaque(true);

        comBoxTo1.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        comBoxTo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engelska", "Svenska" }));
        comBoxTo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxTo1ActionPerformed(evt);
            }
        });

        labelCBDiff.setBackground(new java.awt.Color(106, 78, 57));
        labelCBDiff.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelCBDiff.setForeground(new java.awt.Color(255, 255, 255));
        labelCBDiff.setText("Välj svårighetsgrad:");
        labelCBDiff.setOpaque(true);

        comBoxDiff.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        comBoxDiff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vilken som", "Svår", "Mellan", "Lätt" }));

        labelRBSelectType.setBackground(new java.awt.Color(106, 78, 57));
        labelRBSelectType.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelRBSelectType.setForeground(new java.awt.Color(255, 255, 255));
        labelRBSelectType.setText("Välj ord eller skriv själv:");
        labelRBSelectType.setOpaque(true);

        radBtnSelectChoices.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        radBtnSelectChoices.setText("Välj ord");
        radBtnSelectChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnSelectChoicesActionPerformed(evt);
            }
        });

        radBtnTypeWord.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        radBtnTypeWord.setText("Skriv själv");

        btnConfirmLangDiff.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnConfirmLangDiff.setText("Bekräfta val");
        btnConfirmLangDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmLangDiffActionPerformed(evt);
            }
        });

        btnLangDiffSelectBack.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnLangDiffSelectBack.setText("Tillbaka");
        btnLangDiffSelectBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLangDiffSelectBackActionPerformed(evt);
            }
        });

        labelChBThreeChoices.setBackground(new java.awt.Color(106, 78, 57));
        labelChBThreeChoices.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelChBThreeChoices.setForeground(new java.awt.Color(255, 255, 255));
        labelChBThreeChoices.setText("Tre försök på varje ord?");
        labelChBThreeChoices.setOpaque(true);

        chBoxThreeChoicesYes.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        chBoxThreeChoicesYes.setText("Ja");
        chBoxThreeChoicesYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBoxThreeChoicesYesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLangDiffSelectLayout = new javax.swing.GroupLayout(panelLangDiffSelect);
        panelLangDiffSelect.setLayout(panelLangDiffSelectLayout);
        panelLangDiffSelectLayout.setHorizontalGroup(
            panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmLangDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addGroup(panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelCBFrom1)
                    .addComponent(comBoxFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCBTo1)
                    .addComponent(comBoxTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCBDiff)
                    .addComponent(comBoxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRBSelectType)
                    .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                        .addComponent(radBtnSelectChoices)
                        .addGap(10, 10, 10)
                        .addComponent(radBtnTypeWord))
                    .addComponent(labelChBThreeChoices)
                    .addComponent(chBoxThreeChoicesYes))
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnLangDiffSelectBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLangDiffSelectLayout.setVerticalGroup(
            panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(labelCBFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comBoxFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(labelCBTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comBoxTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(labelCBDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comBoxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(labelRBSelectType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtnSelectChoices)
                    .addComponent(radBtnTypeWord))
                .addGap(36, 36, 36)
                .addComponent(labelChBThreeChoices)
                .addGap(18, 18, 18)
                .addComponent(chBoxThreeChoicesYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnConfirmLangDiff)
                .addGap(23, 23, 23)
                .addComponent(btnLangDiffSelectBack)
                .addGap(58, 58, 58))
        );

        getContentPane().add(panelLangDiffSelect, "card3");

        btnStartGame.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnStartGame.setText("Starta!");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        labelPreGame1.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGame1.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGame1.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame1.setText("Om du vill starta spelet med nedanstående inställningar, tryck på Starta!");
        labelPreGame1.setOpaque(true);

        labelPreGame2.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGame2.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGame2.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame2.setText("Om du vill ändra någon inställning, tryck Tillbaka.");
        labelPreGame2.setOpaque(true);

        labelPreGame3.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGame3.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGame3.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame3.setText("Från-språk:");
        labelPreGame3.setOpaque(true);

        labelPreGame4.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGame4.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGame4.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame4.setText("Till-språk:");
        labelPreGame4.setOpaque(true);

        labelPreGameFrom.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGameFrom.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGameFrom.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGameFrom.setText("<value>");
        labelPreGameFrom.setOpaque(true);

        labelPreGameTo.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGameTo.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGameTo.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGameTo.setText("<value>");
        labelPreGameTo.setOpaque(true);

        labelPreGame5.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGame5.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGame5.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame5.setText("Svårighetsgrad:");
        labelPreGame5.setOpaque(true);

        labelPreGameDiff.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGameDiff.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGameDiff.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGameDiff.setText("<value>");
        labelPreGameDiff.setOpaque(true);

        labelPreGame6.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGame6.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGame6.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame6.setText("Välj ord / skriv själv:");
        labelPreGame6.setOpaque(true);

        labelPreGameSelectType.setBackground(new java.awt.Color(106, 78, 57));
        labelPreGameSelectType.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelPreGameSelectType.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGameSelectType.setText("<value>");
        labelPreGameSelectType.setOpaque(true);

        btnPreGameBack.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnPreGameBack.setText("Tillbaka");
        btnPreGameBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreGameBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPreGameLayout = new javax.swing.GroupLayout(panelPreGame);
        panelPreGame.setLayout(panelPreGameLayout);
        panelPreGameLayout.setHorizontalGroup(
            panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreGameLayout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPreGame2)
                    .addComponent(labelPreGame1)
                    .addGroup(panelPreGameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPreGame3)
                            .addComponent(labelPreGame4)
                            .addComponent(labelPreGame5)
                            .addComponent(labelPreGame6))
                        .addGap(57, 57, 57)
                        .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPreGameTo)
                            .addComponent(labelPreGameFrom)
                            .addComponent(labelPreGameDiff)
                            .addComponent(labelPreGameSelectType))))
                .addGap(0, 233, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreGameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(panelPreGameLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnPreGameBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPreGameLayout.setVerticalGroup(
            panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreGameLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(labelPreGame1)
                .addGap(18, 18, 18)
                .addComponent(labelPreGame2)
                .addGap(50, 50, 50)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreGame3)
                    .addComponent(labelPreGameFrom))
                .addGap(18, 18, 18)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreGame4)
                    .addComponent(labelPreGameTo))
                .addGap(18, 18, 18)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreGame5)
                    .addComponent(labelPreGameDiff))
                .addGap(18, 18, 18)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreGame6)
                    .addComponent(labelPreGameSelectType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnStartGame)
                .addGap(117, 117, 117)
                .addComponent(btnPreGameBack)
                .addGap(57, 57, 57))
        );

        getContentPane().add(panelPreGame, "card4");

        btnNext.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnNext.setText("Svara");

        txtFldAnswer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFldAnswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFldAnswerFocusGained(evt);
            }
        });

        labelWordToTranslate.setBackground(new java.awt.Color(106, 78, 57));
        labelWordToTranslate.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        labelWordToTranslate.setForeground(new java.awt.Color(255, 255, 255));
        labelWordToTranslate.setText("<word to translate>");

        labelWordNo.setBackground(new java.awt.Color(106, 78, 57));
        labelWordNo.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        labelWordNo.setForeground(new java.awt.Color(255, 255, 255));
        labelWordNo.setText("<word no>");

        labelEndGame.setBackground(new java.awt.Color(106, 78, 57));
        labelEndGame.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelEndGame.setForeground(new java.awt.Color(255, 255, 255));

        btnEndGame.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnEndGame.setText("Avsluta spelomgång");
        btnEndGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndGameActionPerformed(evt);
            }
        });

        panelGameTest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelGameTest.setPreferredSize(new java.awt.Dimension(600, 728));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("P L A C E H O L D E R");

        javax.swing.GroupLayout panelGameTest2Layout = new javax.swing.GroupLayout(panelGameTest2);
        panelGameTest2.setLayout(panelGameTest2Layout);
        panelGameTest2Layout.setHorizontalGroup(
            panelGameTest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGameTest2Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        panelGameTest2Layout.setVerticalGroup(
            panelGameTest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameTest2Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGameTestLayout = new javax.swing.GroupLayout(panelGameTest);
        panelGameTest.setLayout(panelGameTestLayout);
        panelGameTestLayout.setHorizontalGroup(
            panelGameTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGameTest2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGameTestLayout.setVerticalGroup(
            panelGameTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGameTest2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        comBoxThreeWords.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        comBoxThreeWords.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "longlonglongword", "mediumword", "shortwd" }));

        labelCBThreeWords.setBackground(new java.awt.Color(106, 78, 57));
        labelCBThreeWords.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelCBThreeWords.setForeground(new java.awt.Color(255, 255, 255));
        labelCBThreeWords.setText("Välj ord i listan");
        labelCBThreeWords.setOpaque(true);

        scrPaneFeedback2.setBackground(new java.awt.Color(255, 255, 255));
        scrPaneFeedback2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrPaneFeedback2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        scrPaneFeedback1.setBackground(new java.awt.Color(255, 255, 255));
        scrPaneFeedback1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrPaneFeedback1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        labelFeedback.setEditable(false);
        labelFeedback.setColumns(20);
        labelFeedback.setFont(new java.awt.Font("Californian FB", 1, 15)); // NOI18N
        labelFeedback.setLineWrap(true);
        labelFeedback.setRows(5);
        labelFeedback.setMinimumSize(new java.awt.Dimension(275, 89));
        labelFeedback.setOpaque(false);
        scrPaneFeedback1.setViewportView(labelFeedback);

        scrPaneFeedback2.setViewportView(scrPaneFeedback1);

        javax.swing.GroupLayout panelGameLayout = new javax.swing.GroupLayout(panelGame);
        panelGame.setLayout(panelGameLayout);
        panelGameLayout.setHorizontalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGameTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPaneFeedback2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addComponent(txtFldAnswer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelEndGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addComponent(comBoxThreeWords, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCBThreeWords)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addComponent(labelWordNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelWordToTranslate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(648, 648, 648)
                .addComponent(btnEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGameLayout.setVerticalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWordToTranslate)
                    .addComponent(labelWordNo))
                .addGap(33, 33, 33)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comBoxThreeWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCBThreeWords))
                .addGap(34, 34, 34)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(txtFldAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrPaneFeedback2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(btnEndGame)
                .addGap(28, 28, 28))
            .addGroup(panelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGameTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelGame, "card5");

        btnSettingsBack.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnSettingsBack.setText("Tillbaka");
        btnSettingsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsBackActionPerformed(evt);
            }
        });

        labelSettings.setBackground(new java.awt.Color(106, 78, 57));
        labelSettings.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        labelSettings.setForeground(new java.awt.Color(255, 255, 255));
        labelSettings.setText("INSTÄLLNINGAR");
        labelSettings.setOpaque(true);

        javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
        panelSettings.setLayout(panelSettingsLayout);
        panelSettingsLayout.setHorizontalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSettingsLayout.createSequentialGroup()
                .addContainerGap(395, Short.MAX_VALUE)
                .addComponent(labelSettings)
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnSettingsBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSettingsLayout.setVerticalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labelSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                .addComponent(btnSettingsBack)
                .addGap(58, 58, 58))
        );

        getContentPane().add(panelSettings, "card6");

        btnHelpBack.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnHelpBack.setText("Tillbaka");
        btnHelpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpBackActionPerformed(evt);
            }
        });

        labelHelp.setBackground(new java.awt.Color(106, 78, 57));
        labelHelp.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        labelHelp.setForeground(new java.awt.Color(255, 255, 255));
        labelHelp.setText("HJÄLP");
        labelHelp.setOpaque(true);

        javax.swing.GroupLayout panelHelpLayout = new javax.swing.GroupLayout(panelHelp);
        panelHelp.setLayout(panelHelpLayout);
        panelHelpLayout.setHorizontalGroup(
            panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHelpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelHelp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelHelpLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnHelpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(764, Short.MAX_VALUE))
        );
        panelHelpLayout.setVerticalGroup(
            panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHelpLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labelHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 574, Short.MAX_VALUE)
                .addComponent(btnHelpBack)
                .addGap(53, 53, 53))
        );

        getContentPane().add(panelHelp, "card7");

        btnHighscoreBack.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnHighscoreBack.setText("Tillbaka till huvudmenyn");
        btnHighscoreBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighscoreBackActionPerformed(evt);
            }
        });

        txtPaneHighscore.setEditable(false);
        txtPaneHighscore.setFont(new java.awt.Font("Californian FB", 0, 15)); // NOI18N
        txtPaneHighscore.setText("Namn\t\tTyp\t\tDatum\t\tPoäng\n\nPelle\t\tn/a\t\t2014-01-01\t\t10");
        scrPaneHighscore.setViewportView(txtPaneHighscore);

        labelHighscore.setBackground(new java.awt.Color(106, 78, 57));
        labelHighscore.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        labelHighscore.setForeground(new java.awt.Color(255, 255, 255));
        labelHighscore.setText("TOPPLISTA");
        labelHighscore.setOpaque(true);

        javax.swing.GroupLayout panelHighscoreLayout = new javax.swing.GroupLayout(panelHighscore);
        panelHighscore.setLayout(panelHighscoreLayout);
        panelHighscoreLayout.setHorizontalGroup(
            panelHighscoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHighscoreLayout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(labelHighscore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHighscoreLayout.createSequentialGroup()
                .addGap(0, 196, Short.MAX_VALUE)
                .addComponent(scrPaneHighscore, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(panelHighscoreLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnHighscoreBack, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHighscoreLayout.setVerticalGroup(
            panelHighscoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHighscoreLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labelHighscore)
                .addGap(42, 42, 42)
                .addComponent(scrPaneHighscore, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(btnHighscoreBack)
                .addGap(48, 48, 48))
        );

        getContentPane().add(panelHighscore, "card8");

        btnAddWordBack.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnAddWordBack.setText("Tillbaka");
        btnAddWordBack.setPreferredSize(new java.awt.Dimension(96, 29));
        btnAddWordBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordBackActionPerformed(evt);
            }
        });

        labelCBFrom2.setBackground(new java.awt.Color(106, 78, 57));
        labelCBFrom2.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelCBFrom2.setForeground(new java.awt.Color(255, 255, 255));
        labelCBFrom2.setText("Från:");
        labelCBFrom2.setOpaque(true);

        txtFldAddWordFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        comBoxFrom2.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        comBoxFrom2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Svenska", "Engelska" }));

        labelAddWordFromError.setBackground(new java.awt.Color(106, 78, 57));
        labelAddWordFromError.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelAddWordFromError.setForeground(new java.awt.Color(255, 255, 255));
        labelAddWordFromError.setText("<input error field>");
        labelAddWordFromError.setOpaque(true);

        labelCBTo2.setBackground(new java.awt.Color(106, 78, 57));
        labelCBTo2.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelCBTo2.setForeground(new java.awt.Color(255, 255, 255));
        labelCBTo2.setText("Till:");
        labelCBTo2.setOpaque(true);

        comBoxTo2.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        comBoxTo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engelska", "Svenska" }));

        txtFldAddWordTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelAddWordToError.setBackground(new java.awt.Color(106, 78, 57));
        labelAddWordToError.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelAddWordToError.setForeground(new java.awt.Color(255, 255, 255));
        labelAddWordToError.setText("<input error field>");
        labelAddWordToError.setOpaque(true);

        txtFldAddWordNewLang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAddWordAdd.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnAddWordAdd.setText("Lägg till glosa");

        btnAddWordClear.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnAddWordClear.setText("Rensa fält");
        btnAddWordClear.setMaximumSize(new java.awt.Dimension(60, 29));
        btnAddWordClear.setMinimumSize(new java.awt.Dimension(60, 29));
        btnAddWordClear.setPreferredSize(new java.awt.Dimension(60, 29));

        labelSubmitNewLang.setBackground(new java.awt.Color(106, 78, 57));
        labelSubmitNewLang.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelSubmitNewLang.setForeground(new java.awt.Color(255, 255, 255));
        labelSubmitNewLang.setText("Nytt språk:");
        labelSubmitNewLang.setOpaque(true);

        btnNewLangSave.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnNewLangSave.setLabel("Spara");
        btnNewLangSave.setPreferredSize(new java.awt.Dimension(59, 29));

        labelHighscore1.setBackground(new java.awt.Color(106, 78, 57));
        labelHighscore1.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        labelHighscore1.setForeground(new java.awt.Color(255, 255, 255));
        labelHighscore1.setText("LÄGG TILL GLOSA");
        labelHighscore1.setOpaque(true);

        javax.swing.GroupLayout panelAddWordLayout = new javax.swing.GroupLayout(panelAddWord);
        panelAddWord.setLayout(panelAddWordLayout);
        panelAddWordLayout.setHorizontalGroup(
            panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddWordLayout.createSequentialGroup()
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(txtFldAddWordFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comBoxFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCBTo2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoxTo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCBFrom2)))
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddWordClear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldAddWordTo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 48, Short.MAX_VALUE)
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddWordFromError, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubmitNewLang)
                    .addComponent(labelAddWordToError, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddWordAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addComponent(txtFldAddWordNewLang, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewLangSave, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(348, 348, 348))
            .addGroup(panelAddWordLayout.createSequentialGroup()
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAddWordBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHighscore1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAddWordLayout.setVerticalGroup(
            panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddWordLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labelHighscore1)
                .addGap(48, 48, 48)
                .addComponent(labelCBFrom2)
                .addGap(7, 7, 7)
                .addComponent(comBoxFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFldAddWordFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAddWordFromError))
                        .addGap(67, 67, 67)
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCBTo2)
                            .addComponent(labelSubmitNewLang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comBoxTo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldAddWordNewLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNewLangSave, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFldAddWordTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAddWordToError))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddWordAdd)
                            .addComponent(btnAddWordClear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(130, 130, 130)
                .addComponent(btnAddWordBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        getContentPane().add(panelAddWord, "card9");

        btnListWordsBack.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnListWordsBack.setText("Tillbaka");
        btnListWordsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListWordsBackActionPerformed(evt);
            }
        });

        scrPaneListWords.setViewportView(jEditorPane1);

        labelCBFrom3.setBackground(new java.awt.Color(106, 78, 57));
        labelCBFrom3.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelCBFrom3.setForeground(new java.awt.Color(255, 255, 255));
        labelCBFrom3.setText("Från:");
        labelCBFrom3.setOpaque(true);

        comBoxFrom3.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        comBoxFrom3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Svenska", "Engelska" }));

        labelCBTo3.setBackground(new java.awt.Color(106, 78, 57));
        labelCBTo3.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        labelCBTo3.setForeground(new java.awt.Color(255, 255, 255));
        labelCBTo3.setText("Till:");
        labelCBTo3.setOpaque(true);

        comBoxTo3.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        comBoxTo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engelska", "Svenska" }));

        btnListWordsSave.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnListWordsSave.setText("Spara ändringar");

        btnListWordsShow.setFont(new java.awt.Font("Californian FB", 1, 16)); // NOI18N
        btnListWordsShow.setText("Visa lista");

        labelHighscore2.setBackground(new java.awt.Color(106, 78, 57));
        labelHighscore2.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        labelHighscore2.setForeground(new java.awt.Color(255, 255, 255));
        labelHighscore2.setText("LISTA GLOSOR");
        labelHighscore2.setOpaque(true);

        javax.swing.GroupLayout panelListWordsLayout = new javax.swing.GroupLayout(panelListWords);
        panelListWords.setLayout(panelListWordsLayout);
        panelListWordsLayout.setHorizontalGroup(
            panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListWordsLayout.createSequentialGroup()
                .addGap(0, 405, Short.MAX_VALUE)
                .addComponent(labelHighscore2)
                .addGap(402, 402, 402))
            .addGroup(panelListWordsLayout.createSequentialGroup()
                .addGroup(panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListWordsLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnListWordsBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelListWordsLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnListWordsSave, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(scrPaneListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelListWordsLayout.createSequentialGroup()
                                    .addComponent(labelCBFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comBoxFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(labelCBTo3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comBoxTo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(btnListWordsShow, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelListWordsLayout.setVerticalGroup(
            panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListWordsLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labelHighscore2)
                .addGap(88, 88, 88)
                .addGroup(panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCBFrom3)
                    .addComponent(comBoxFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCBTo3)
                    .addComponent(comBoxTo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListWordsShow))
                .addGap(18, 18, 18)
                .addComponent(scrPaneListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListWordsSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnListWordsBack)
                .addGap(64, 64, 64))
        );

        getContentPane().add(panelListWords, "card10");

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void displaySplashScreen() 
    {
        JWindow window = new JWindow();
        ImageIcon splashIcon = new ImageIcon("images/splash2.png");
        window.getContentPane().add(new JLabel("", splashIcon, SwingConstants.CENTER));
        int splashWidth = splashIcon.getIconWidth();
        int splashHeight = splashIcon.getIconHeight();        
        window.setBounds(screenSize.width / 2 - (splashWidth / 2), screenSize.height / 2 - (splashHeight / 2), splashWidth, splashHeight);
        window.setVisible(true);
               
        // delay
        try 
        {            
            Thread.sleep(splashDelayInSeconds * 1000);
        } 
        catch (InterruptedException e) 
        {            
        }
        window.setVisible(false);
        window.dispose();
    }    
    
    private void createGroupSelectOrType()
    {
        groupSelectOrType = new ButtonGroup();
        groupSelectOrType.add(radBtnSelectChoices);
        groupSelectOrType.add(radBtnTypeWord);
        radBtnTypeWord.setSelected(true);  
    }
    
    public void enableAnswerButton()
    {
        btnNext.setEnabled(true);
    }    
    
    public void disableAnswerButton()
    {
        btnNext.setEnabled(false);
    }
    
    /**
     * Add a listener for the new game button
     * @param listener listener to add
     */
    public void initiateAddListener(ActionListener listener) 
    {
        btnStartGame.addActionListener(listener); 
    }
    
    /**
     * Add a listener for the next (answer) button
     * @param listener listener to add
     */    
    public void nextAddListener(ActionListener listener) 
    {        
        btnNext.addActionListener(listener); 
    }
    
    /**
     * L8
     * Add a listener for end game that will ask for user
     * @param listener listener to add
     */
    public void addEndGameListener(ActionListener listener) 
    {        
        btnEndGame.addActionListener(listener);
    }
    
    /**
     * L8 
     * Gets the user name to add result for
     * @return The user name entered
     */
    public String getUser() {
        String input; 
        input = JOptionPane.showInputDialog("Skriv in ditt namn:");
        return input;
    }
    
    /**
     * L8
     * Add a listener for the confirm choice button button
     * @param listener listener to add
     */    
    public void confirmChoiceAddListener(ActionListener listener) 
    {        
        btnConfirmLangDiff.addActionListener(listener); 
    }
    
    public void setNewGlossary(String word) 
    {        
        labelWordToTranslate.setText(word);        
    }
    
    public void setGlossaryNumber(int no) 
    {
        String text;
        text = Integer.toString(no);        
        labelWordNo.setText(text + ". "); 
    }
    
    public String getAnswer() 
    {
        String answer = "";        
        answer = txtFldAnswer.getText();
        return answer;
    }
    
    public void setErrorText(String errorMessage) 
    {        
        System.out.println("L8 setErrorText");
        labelFeedback.setOpaque(true);        
        labelFeedback.setForeground(Color.red); 
        labelFeedback.setText(errorMessage);
                 
        // test
        scrPaneFeedback1.setVisible(true);
        scrPaneFeedback2.setVisible(true);
        
        System.out.println(errorMessage);
    }
    
    public void setCorrectText(String message) 
    {
        labelFeedback.setOpaque(true);
        labelFeedback.setForeground(Color.blue); 
        labelFeedback.setText(message);   
                
        // test
        scrPaneFeedback1.setVisible(true);
        scrPaneFeedback2.setVisible(true);
        
        System.out.println(message);       
    }
    
    public void setEmptyAnswer() 
    {        
        txtFldAnswer.setText("");        
    }
     
    public void setEndText(int total, int correct) 
    {     
        labelEndGame.setOpaque(true);
        labelEndGame.setText("Du hade " + correct + " rätt av " + total + ".");
    }
    
    /**
     * L8
     * Checks if user want to write the words him/herself or if the user want to
     * select from a list of words
     * @return true if user want to write own word, else false
     */
    public Boolean isWriteWordSelected() 
    {
        Boolean writeOwnWord;
        if (radBtnTypeWord.isSelected()) 
        {
            writeOwnWord = true;
        }
        else 
        {
            writeOwnWord = false;
        }
        return writeOwnWord;
    }
    
    /**
     * L8 
     * Writes three alternatives in text field
     * @param wordAlternatives An arrayList with the alternatives
     */
    public void setWordAlternatives(ArrayList<String> wordAlternatives) 
    {
        String tmpString;
        tmpString = "";
        for (int i = 0; i < wordAlternatives.size(); i++) 
        {
             tmpString = tmpString + ";" + wordAlternatives.get(i);
        }
        txtFldAnswer.setText(tmpString);
    }
    
    public void setEmptyEndText()
    {
        labelEndGame.setText("");
    }
    
    public void setEmptyFeedbackText()
    {
        System.out.println("L8 setEmptyFeedBackText");
        labelFeedback.setText("");
        labelFeedback.setOpaque(false);
                
        // test
        scrPaneFeedback1.setVisible(false);
        scrPaneFeedback2.setVisible(false);
    }   
    
    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        
        panelMainMenu.setVisible(false);
        panelLangDiffSelect.setVisible(true);        
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void comBoxFrom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxFrom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxFrom1ActionPerformed

    private void radBtnSelectChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnSelectChoicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnSelectChoicesActionPerformed

    private void btnConfirmLangDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmLangDiffActionPerformed
        
        panelLangDiffSelect.setVisible(false);
        panelPreGame.setVisible(true);        
    }//GEN-LAST:event_btnConfirmLangDiffActionPerformed

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        
        panelPreGame.setVisible(false);
        panelGame.setVisible(true);        
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void labelSettingsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSettingsIconMouseClicked
        
        panelMainMenu.setVisible(false);
        panelSettings.setVisible(true);        
    }//GEN-LAST:event_labelSettingsIconMouseClicked

    private void btnSettingsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsBackActionPerformed
        
        panelSettings.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnSettingsBackActionPerformed

    private void labelHelpIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHelpIconMouseClicked
        
        panelMainMenu.setVisible(false);
        panelHelp.setVisible(true);         
    }//GEN-LAST:event_labelHelpIconMouseClicked

    private void btnHelpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpBackActionPerformed
        
        panelHelp.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnHelpBackActionPerformed

    private void btnHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighScoreActionPerformed
        
        panelMainMenu.setVisible(false);
        panelHighscore.setVisible(true); 
    }//GEN-LAST:event_btnHighScoreActionPerformed

    private void btnAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordActionPerformed
        
        panelMainMenu.setVisible(false);
        panelAddWord.setVisible(true);  
    }//GEN-LAST:event_btnAddWordActionPerformed

    private void btnListWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListWordsActionPerformed
        
        panelMainMenu.setVisible(false);
        panelListWords.setVisible(true);  
    }//GEN-LAST:event_btnListWordsActionPerformed

    private void btnHighscoreBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighscoreBackActionPerformed
        
        panelHighscore.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnHighscoreBackActionPerformed

    private void btnAddWordBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordBackActionPerformed
        
        panelAddWord.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnAddWordBackActionPerformed

    private void btnListWordsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListWordsBackActionPerformed
        
        panelListWords.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnListWordsBackActionPerformed

    private void btnLangDiffSelectBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLangDiffSelectBackActionPerformed
        
        panelLangDiffSelect.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnLangDiffSelectBackActionPerformed

    private void btnEndGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndGameActionPerformed
        
        //L8 removed this String input = JOptionPane.showInputDialog("Skriv in ditt namn:");
        
        // TODO add end game handling code here (for saving score, user name ?)
        
        panelGame.setVisible(false);
        panelHighscore.setVisible(true); 
    }//GEN-LAST:event_btnEndGameActionPerformed

    private void btnPreGameBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreGameBackActionPerformed
               
        panelPreGame.setVisible(false);
        panelLangDiffSelect.setVisible(true); 
    }//GEN-LAST:event_btnPreGameBackActionPerformed

    private void chBoxThreeChoicesYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBoxThreeChoicesYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chBoxThreeChoicesYesActionPerformed

    private void txtFldAnswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldAnswerFocusGained
               
        System.out.println("L8 txtFldAnswerFocusGained");
        labelFeedback.setOpaque(false);
        labelFeedback.setText("");
                
        // test
        scrPaneFeedback1.setVisible(false);
        scrPaneFeedback2.setVisible(false);
    }//GEN-LAST:event_txtFldAnswerFocusGained

    private void comBoxTo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxTo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxTo1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWord;
    private javax.swing.JButton btnAddWordAdd;
    private javax.swing.JButton btnAddWordBack;
    private javax.swing.JButton btnAddWordClear;
    private javax.swing.JButton btnConfirmLangDiff;
    private javax.swing.JButton btnEndGame;
    private javax.swing.JButton btnHelpBack;
    private javax.swing.JButton btnHighScore;
    private javax.swing.JButton btnHighscoreBack;
    private javax.swing.JButton btnLangDiffSelectBack;
    private javax.swing.JButton btnListWords;
    private javax.swing.JButton btnListWordsBack;
    private javax.swing.JButton btnListWordsSave;
    private javax.swing.JButton btnListWordsShow;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnNewLangSave;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPreGameBack;
    private javax.swing.JButton btnSettingsBack;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JCheckBox chBoxThreeChoicesYes;
    private javax.swing.JComboBox comBoxDiff;
    private javax.swing.JComboBox comBoxFrom1;
    private javax.swing.JComboBox comBoxFrom2;
    private javax.swing.JComboBox comBoxFrom3;
    private javax.swing.JComboBox comBoxThreeWords;
    private javax.swing.JComboBox comBoxTo1;
    private javax.swing.JComboBox comBoxTo2;
    private javax.swing.JComboBox comBoxTo3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAddWordFromError;
    private javax.swing.JLabel labelAddWordToError;
    private javax.swing.JLabel labelCBDiff;
    private javax.swing.JLabel labelCBFrom1;
    private javax.swing.JLabel labelCBFrom2;
    private javax.swing.JLabel labelCBFrom3;
    private javax.swing.JLabel labelCBThreeWords;
    private javax.swing.JLabel labelCBTo1;
    private javax.swing.JLabel labelCBTo2;
    private javax.swing.JLabel labelCBTo3;
    private javax.swing.JLabel labelChBThreeChoices;
    private javax.swing.JLabel labelEndGame;
    private javax.swing.JTextArea labelFeedback;
    private javax.swing.JLabel labelHelp;
    private javax.swing.JLabel labelHelpIcon;
    private javax.swing.JLabel labelHighscore;
    private javax.swing.JLabel labelHighscore1;
    private javax.swing.JLabel labelHighscore2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPreGame1;
    private javax.swing.JLabel labelPreGame2;
    private javax.swing.JLabel labelPreGame3;
    private javax.swing.JLabel labelPreGame4;
    private javax.swing.JLabel labelPreGame5;
    private javax.swing.JLabel labelPreGame6;
    private javax.swing.JLabel labelPreGameDiff;
    private javax.swing.JLabel labelPreGameFrom;
    private javax.swing.JLabel labelPreGameSelectType;
    private javax.swing.JLabel labelPreGameTo;
    private javax.swing.JLabel labelRBSelectType;
    private javax.swing.JLabel labelSettings;
    private javax.swing.JLabel labelSettingsIcon;
    private javax.swing.JLabel labelSubmitNewLang;
    private javax.swing.JLabel labelWordNo;
    private javax.swing.JLabel labelWordToTranslate;
    private javax.swing.JPanel panelAddWord;
    private javax.swing.JPanel panelGame;
    private javax.swing.JPanel panelGameTest;
    private javax.swing.JPanel panelGameTest2;
    private javax.swing.JPanel panelHelp;
    private javax.swing.JPanel panelHighscore;
    private javax.swing.JPanel panelLangDiffSelect;
    private javax.swing.JPanel panelListWords;
    private javax.swing.JPanel panelMainMenu;
    private javax.swing.JPanel panelPreGame;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JRadioButton radBtnSelectChoices;
    private javax.swing.JRadioButton radBtnTypeWord;
    private javax.swing.JScrollPane scrPaneFeedback1;
    private javax.swing.JScrollPane scrPaneFeedback2;
    private javax.swing.JScrollPane scrPaneHighscore;
    private javax.swing.JScrollPane scrPaneListWords;
    private javax.swing.JTextField txtFldAddWordFrom;
    private javax.swing.JTextField txtFldAddWordNewLang;
    private javax.swing.JTextField txtFldAddWordTo;
    private javax.swing.JTextField txtFldAnswer;
    private javax.swing.JTextPane txtPaneHighscore;
    // End of variables declaration//GEN-END:variables
} 
