/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gloskampen.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JWindow;
import javax.swing.SwingConstants;


/**
 * Latest update: 2014-01-07 15:10
 * @author Fredrik Johansson 
 */
public class MainView extends javax.swing.JFrame 
{
    private ButtonGroup groupSelectOrType;
    private final Dimension screenSize;
    private BufferedImage bgImg; 
    private final ButtonStyle btnStyle;
    private final ArrayList<JPanel> allPanels;
    private final int splashDelayInSeconds = 3;
         
    
    /**
     * Creates new form MainView
     */
    public MainView() 
    {      
        this.setResizable(false); // prevent window resizing
        
        // style the window borders a bit
        this.setUndecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.WARNING_DIALOG);
        
        // load background image
        try 
        {
            bgImg = ImageIO.read(new File("images/bgImg3.jpg"));
        } 
        catch(IOException e) 
        {
        }
        
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();         
        displaySplashScreen();        
        initComponents();                  
        this.setLocation(screenSize.width / 2 - this.getSize().width / 2, screenSize.height / 2 - this.getSize().height / 2); 
        createGroupSelectOrType();                   
        allPanels = new ArrayList<>(); 
        
        // add panels to the panel ArrayList
        allPanels.add(panelMainMenu);
        allPanels.add(panelLangDiffSelect);
        allPanels.add(panelPreGame);
        allPanels.add(panelGame);
        allPanels.add(panelSettings);
        allPanels.add(panelHelp);
        allPanels.add(panelHighscore);
        allPanels.add(panelAddWord);
        allPanels.add(panelListWords);
        
        // create new ButtonStyle object to style all buttons
        btnStyle = new ButtonStyle(allPanels);           
    }    
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMainMenu = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        }
        ;
        labelLogo = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnHighScore = new javax.swing.JButton();
        btnAddWord = new javax.swing.JButton();
        btnListWords = new javax.swing.JButton();
        labelSettingsIcon = new javax.swing.JLabel();
        labelHelpIcon = new javax.swing.JLabel();
        panelLangDiffSelect = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelLangDiffSelect = new javax.swing.JLabel();
        labelCBFrom1 = new javax.swing.JLabel();
        comBoxFrom1 = new javax.swing.JComboBox();
        labelCBTo1 = new javax.swing.JLabel();
        comBoxTo1 = new javax.swing.JComboBox();
        labelCBDiff = new javax.swing.JLabel();
        comBoxDiff = new javax.swing.JComboBox();
        labelRBSelectType = new javax.swing.JLabel();
        radBtnSelectChoices = new javax.swing.JRadioButton();
        radBtnTypeWord = new javax.swing.JRadioButton();
        btnConfirmLangDiff = new javax.swing.JButton();
        btnLangDiffSelectBack = new javax.swing.JButton();
        labelChBThreeChoices = new javax.swing.JLabel();
        chBoxThreeChoicesYes = new javax.swing.JCheckBox();
        panelPreGame = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelPreGame = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        labelPreGame1 = new javax.swing.JLabel();
        labelPreGame2 = new javax.swing.JLabel();
        labelPreGame3 = new javax.swing.JLabel();
        labelPreGame4 = new javax.swing.JLabel();
        labelPreGameFrom = new javax.swing.JLabel();
        labelPreGameTo = new javax.swing.JLabel();
        labelPreGame5 = new javax.swing.JLabel();
        labelPreGameDiff = new javax.swing.JLabel();
        labelPreGame6 = new javax.swing.JLabel();
        labelPreGameSelectType = new javax.swing.JLabel();
        btnPreGameBack = new javax.swing.JButton();
        panelGame = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelGame = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        txtFldAnswer = new javax.swing.JTextField();
        labelWordToTranslate = new javax.swing.JLabel();
        labelWordNo = new javax.swing.JLabel();
        labelEndGame = new javax.swing.JLabel();
        btnEndGame = new javax.swing.JButton();
        panelGameTest = new javax.swing.JPanel();
        panelGameTest2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comBoxThreeWords = new javax.swing.JComboBox();
        labelCBThreeWords = new javax.swing.JLabel();
        scrPaneFeedback2 = new javax.swing.JScrollPane();
        scrPaneFeedback1 = new javax.swing.JScrollPane();
        labelFeedback = new javax.swing.JTextArea();
        panelSettings = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelSettings = new javax.swing.JLabel();
        btnSettingsBack = new javax.swing.JButton();
        panelHelp = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelHelp = new javax.swing.JLabel();
        btnHelpBack = new javax.swing.JButton();
        panelHighscore = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelHighscore = new javax.swing.JLabel();
        btnHighscoreBack = new javax.swing.JButton();
        scrPaneHighscore = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        panelAddWord = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelAddWord = new javax.swing.JLabel();
        btnAddWordBack = new javax.swing.JButton();
        labelCBFrom2 = new javax.swing.JLabel();
        txtFldAddWordFrom = new javax.swing.JTextField();
        comBoxFrom2 = new javax.swing.JComboBox();
        labelAddWordFromError = new javax.swing.JLabel();
        labelCBTo2 = new javax.swing.JLabel();
        comBoxTo2 = new javax.swing.JComboBox();
        txtFldAddWordTo = new javax.swing.JTextField();
        labelAddWordToError = new javax.swing.JLabel();
        txtFldAddWordNewLang = new javax.swing.JTextField();
        btnAddWordAdd = new javax.swing.JButton();
        btnAddWordClear = new javax.swing.JButton();
        labelSubmitNewLang = new javax.swing.JLabel();
        btnNewLangOK = new javax.swing.JButton();
        panelListWords = new javax.swing.JPanel()
        {
            // test
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                // paint the background image and scale it to fill the entire space
                g.drawImage(bgImg, 0, 0, getWidth(), getHeight(), this);
            }
        };
        labelListWords = new javax.swing.JLabel();
        btnListWordsBack = new javax.swing.JButton();
        scrPaneListWords = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        labelCBFrom3 = new javax.swing.JLabel();
        comBoxFrom3 = new javax.swing.JComboBox();
        labelCBTo3 = new javax.swing.JLabel();
        comBoxTo3 = new javax.swing.JComboBox();
        btnListWordsSave = new javax.swing.JButton();
        btnListWordsShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gloskampen");
        getContentPane().setLayout(new java.awt.CardLayout());

        panelMainMenu.setPreferredSize(new java.awt.Dimension(960, 750));

        labelLogo.setFont(new java.awt.Font("Stencil Std", 1, 31)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(154, 111, 77));
        labelLogo.setText("GLOSKAMPEN");

        btnNewGame.setFont(new java.awt.Font("Californian FB", 1, 17)); // NOI18N
        btnNewGame.setText("Nytt spel");
        btnNewGame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewGame.setFocusPainted(false);
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnHighScore.setFont(new java.awt.Font("Californian FB", 1, 17)); // NOI18N
        btnHighScore.setText("Topplista");
        btnHighScore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighScoreActionPerformed(evt);
            }
        });

        btnAddWord.setFont(new java.awt.Font("Californian FB", 1, 17)); // NOI18N
        btnAddWord.setText("Lägg till glosa");
        btnAddWord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordActionPerformed(evt);
            }
        });

        btnListWords.setFont(new java.awt.Font("Californian FB", 1, 17)); // NOI18N
        btnListWords.setText("Lista glosor");
        btnListWords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListWordsActionPerformed(evt);
            }
        });

        labelSettingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gloskampen/view/images/wrench2.png"))); // NOI18N
        labelSettingsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSettingsIconMouseClicked(evt);
            }
        });

        labelHelpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gloskampen/view/images/help6.png"))); // NOI18N
        labelHelpIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHelpIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMainMenuLayout = new javax.swing.GroupLayout(panelMainMenu);
        panelMainMenu.setLayout(panelMainMenuLayout);
        panelMainMenuLayout.setHorizontalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenuLayout.createSequentialGroup()
                .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainMenuLayout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnListWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddWord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHighScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNewGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMainMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelSettingsIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpIcon))
                    .addGroup(panelMainMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        panelMainMenuLayout.setVerticalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHelpIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSettingsIcon))
                .addGap(71, 71, 71)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHighScore, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        getContentPane().add(panelMainMenu, "card2");

        labelLangDiffSelect.setForeground(new java.awt.Color(255, 255, 255));
        labelLangDiffSelect.setText("(panelLangDiffSelect)");

        labelCBFrom1.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelCBFrom1.setForeground(new java.awt.Color(255, 255, 255));
        labelCBFrom1.setText("Välj från-språk:");

        comBoxFrom1.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        comBoxFrom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Svenska", "Engelska" }));
        comBoxFrom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxFrom1ActionPerformed(evt);
            }
        });

        labelCBTo1.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelCBTo1.setForeground(new java.awt.Color(255, 255, 255));
        labelCBTo1.setText("Välj till-språk:");

        comBoxTo1.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        comBoxTo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engelska", "Svenska" }));

        labelCBDiff.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelCBDiff.setForeground(new java.awt.Color(255, 255, 255));
        labelCBDiff.setText("Välj svårighetsgrad:");

        comBoxDiff.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        comBoxDiff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vilken som", "Svår", "Mellan", "Lätt" }));

        labelRBSelectType.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelRBSelectType.setForeground(new java.awt.Color(255, 255, 255));
        labelRBSelectType.setText("Välj ord eller skriv själv:");

        radBtnSelectChoices.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        radBtnSelectChoices.setText("Välj ord");
        radBtnSelectChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnSelectChoicesActionPerformed(evt);
            }
        });

        radBtnTypeWord.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        radBtnTypeWord.setText("Skriv själv");

        btnConfirmLangDiff.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnConfirmLangDiff.setText("Bekräfta val");
        btnConfirmLangDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmLangDiffActionPerformed(evt);
            }
        });

        btnLangDiffSelectBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnLangDiffSelectBack.setText("Tillbaka");
        btnLangDiffSelectBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLangDiffSelectBackActionPerformed(evt);
            }
        });

        labelChBThreeChoices.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelChBThreeChoices.setForeground(new java.awt.Color(255, 255, 255));
        labelChBThreeChoices.setText("Tre försök på varje ord?");

        chBoxThreeChoicesYes.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        chBoxThreeChoicesYes.setText("Ja");
        chBoxThreeChoicesYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBoxThreeChoicesYesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLangDiffSelectLayout = new javax.swing.GroupLayout(panelLangDiffSelect);
        panelLangDiffSelect.setLayout(panelLangDiffSelectLayout);
        panelLangDiffSelectLayout.setHorizontalGroup(
            panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmLangDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                .addGroup(panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addGroup(panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelLangDiffSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCBFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoxFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCBTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoxTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCBDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRBSelectType, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                                .addComponent(radBtnSelectChoices)
                                .addGap(10, 10, 10)
                                .addComponent(radBtnTypeWord))
                            .addComponent(labelChBThreeChoices)
                            .addComponent(chBoxThreeChoicesYes)))
                    .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnLangDiffSelectBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        panelLangDiffSelectLayout.setVerticalGroup(
            panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLangDiffSelectLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelLangDiffSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(labelCBFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comBoxFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(labelCBTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comBoxTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(labelCBDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comBoxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(labelRBSelectType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLangDiffSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtnSelectChoices)
                    .addComponent(radBtnTypeWord))
                .addGap(36, 36, 36)
                .addComponent(labelChBThreeChoices)
                .addGap(18, 18, 18)
                .addComponent(chBoxThreeChoicesYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnConfirmLangDiff)
                .addGap(23, 23, 23)
                .addComponent(btnLangDiffSelectBack)
                .addGap(58, 58, 58))
        );

        getContentPane().add(panelLangDiffSelect, "card3");

        labelPreGame.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame.setText("(panelPreGame)");

        btnStartGame.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnStartGame.setText("Starta!");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        labelPreGame1.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGame1.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame1.setText("Om du vill starta spelet med nedanstående inställningar, tryck på Starta!");

        labelPreGame2.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGame2.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame2.setText("Om du vill ändra någon inställning, tryck Tillbaka.");

        labelPreGame3.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGame3.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame3.setText("Från-språk:");

        labelPreGame4.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGame4.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame4.setText("Till-språk:");

        labelPreGameFrom.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGameFrom.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGameFrom.setText("<value>");

        labelPreGameTo.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGameTo.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGameTo.setText("<value>");

        labelPreGame5.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGame5.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame5.setText("Svårighetsgrad:");

        labelPreGameDiff.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGameDiff.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGameDiff.setText("<value>");

        labelPreGame6.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGame6.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGame6.setText("Välj ord / skriv själv:");

        labelPreGameSelectType.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelPreGameSelectType.setForeground(new java.awt.Color(255, 255, 255));
        labelPreGameSelectType.setText("<value>");

        btnPreGameBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnPreGameBack.setText("Tillbaka");
        btnPreGameBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreGameBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPreGameLayout = new javax.swing.GroupLayout(panelPreGame);
        panelPreGame.setLayout(panelPreGameLayout);
        panelPreGameLayout.setHorizontalGroup(
            panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreGameLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPreGame2)
                    .addComponent(labelPreGame1)
                    .addGroup(panelPreGameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPreGame3)
                            .addComponent(labelPreGame4)
                            .addComponent(labelPreGame5)
                            .addComponent(labelPreGame6))
                        .addGap(57, 57, 57)
                        .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPreGameTo)
                            .addComponent(labelPreGameFrom)
                            .addComponent(labelPreGameDiff)
                            .addComponent(labelPreGameSelectType))))
                .addGap(0, 230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreGameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(panelPreGameLayout.createSequentialGroup()
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPreGameLayout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(labelPreGame, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPreGameLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnPreGameBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPreGameLayout.setVerticalGroup(
            panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreGameLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelPreGame, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(labelPreGame1)
                .addGap(18, 18, 18)
                .addComponent(labelPreGame2)
                .addGap(50, 50, 50)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreGame3)
                    .addComponent(labelPreGameFrom))
                .addGap(18, 18, 18)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreGame4)
                    .addComponent(labelPreGameTo))
                .addGap(18, 18, 18)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreGame5)
                    .addComponent(labelPreGameDiff))
                .addGap(18, 18, 18)
                .addGroup(panelPreGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreGame6)
                    .addComponent(labelPreGameSelectType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btnStartGame)
                .addGap(117, 117, 117)
                .addComponent(btnPreGameBack)
                .addGap(57, 57, 57))
        );

        getContentPane().add(panelPreGame, "card4");

        labelGame.setForeground(new java.awt.Color(255, 255, 255));
        labelGame.setText("(panelGame)");

        btnNext.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnNext.setText("Svara");

        txtFldAnswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFldAnswerFocusGained(evt);
            }
        });

        labelWordToTranslate.setFont(new java.awt.Font("Californian FB", 1, 22)); // NOI18N
        labelWordToTranslate.setForeground(new java.awt.Color(255, 255, 255));
        labelWordToTranslate.setText("<word to translate>");

        labelWordNo.setFont(new java.awt.Font("Californian FB", 0, 22)); // NOI18N
        labelWordNo.setForeground(new java.awt.Color(255, 255, 255));
        labelWordNo.setText("<word no>");

        labelEndGame.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelEndGame.setForeground(new java.awt.Color(255, 255, 255));

        btnEndGame.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnEndGame.setText("Avsluta spelomgång");
        btnEndGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndGameActionPerformed(evt);
            }
        });

        panelGameTest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelGameTest.setPreferredSize(new java.awt.Dimension(600, 728));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("P L A C E H O L D E R");

        javax.swing.GroupLayout panelGameTest2Layout = new javax.swing.GroupLayout(panelGameTest2);
        panelGameTest2.setLayout(panelGameTest2Layout);
        panelGameTest2Layout.setHorizontalGroup(
            panelGameTest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGameTest2Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        panelGameTest2Layout.setVerticalGroup(
            panelGameTest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameTest2Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGameTestLayout = new javax.swing.GroupLayout(panelGameTest);
        panelGameTest.setLayout(panelGameTestLayout);
        panelGameTestLayout.setHorizontalGroup(
            panelGameTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGameTest2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGameTestLayout.setVerticalGroup(
            panelGameTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGameTest2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        comBoxThreeWords.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        comBoxThreeWords.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ord1", "ord2", "ord3" }));

        labelCBThreeWords.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelCBThreeWords.setForeground(new java.awt.Color(255, 255, 255));
        labelCBThreeWords.setText("Välj ord i listan");

        scrPaneFeedback2.setBackground(new java.awt.Color(255, 255, 255));
        scrPaneFeedback2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrPaneFeedback2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        scrPaneFeedback1.setBackground(new java.awt.Color(255, 255, 255));
        scrPaneFeedback1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrPaneFeedback1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        labelFeedback.setEditable(false);
        labelFeedback.setColumns(20);
        labelFeedback.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelFeedback.setLineWrap(true);
        labelFeedback.setRows(5);
        labelFeedback.setMinimumSize(new java.awt.Dimension(275, 89));
        labelFeedback.setOpaque(false);
        scrPaneFeedback1.setViewportView(labelFeedback);

        scrPaneFeedback2.setViewportView(scrPaneFeedback1);

        javax.swing.GroupLayout panelGameLayout = new javax.swing.GroupLayout(panelGame);
        panelGame.setLayout(panelGameLayout);
        panelGameLayout.setHorizontalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGameTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(labelEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrPaneFeedback2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelGameLayout.createSequentialGroup()
                                .addComponent(txtFldAnswer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGameLayout.createSequentialGroup()
                                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelGameLayout.createSequentialGroup()
                                        .addComponent(labelWordNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelWordToTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelGameLayout.createSequentialGroup()
                                        .addComponent(comBoxThreeWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelCBThreeWords))
                                    .addComponent(labelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(648, 648, 648)
                .addComponent(btnEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        panelGameLayout.setVerticalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWordToTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWordNo))
                .addGap(30, 30, 30)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comBoxThreeWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCBThreeWords))
                .addGap(34, 34, 34)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(txtFldAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrPaneFeedback2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(labelEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(btnEndGame)
                .addGap(28, 28, 28))
            .addGroup(panelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGameTest, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelGame, "card5");

        labelSettings.setForeground(new java.awt.Color(255, 255, 255));
        labelSettings.setText("(panelSettings)");

        btnSettingsBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnSettingsBack.setText("Tillbaka");
        btnSettingsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
        panelSettings.setLayout(panelSettingsLayout);
        panelSettingsLayout.setHorizontalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnSettingsBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSettingsLayout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addComponent(labelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(425, 425, 425))
        );
        panelSettingsLayout.setVerticalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(labelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE)
                .addComponent(btnSettingsBack)
                .addGap(58, 58, 58))
        );

        getContentPane().add(panelSettings, "card6");

        labelHelp.setForeground(new java.awt.Color(255, 255, 255));
        labelHelp.setText("(panelHelp)");

        btnHelpBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnHelpBack.setText("Tillbaka");
        btnHelpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHelpLayout = new javax.swing.GroupLayout(panelHelp);
        panelHelp.setLayout(panelHelpLayout);
        panelHelpLayout.setHorizontalGroup(
            panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHelpLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnHelpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHelpLayout.createSequentialGroup()
                .addContainerGap(421, Short.MAX_VALUE)
                .addComponent(labelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(429, 429, 429))
        );
        panelHelpLayout.setVerticalGroup(
            panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHelpLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 575, Short.MAX_VALUE)
                .addComponent(btnHelpBack)
                .addGap(53, 53, 53))
        );

        getContentPane().add(panelHelp, "card7");

        labelHighscore.setForeground(new java.awt.Color(255, 255, 255));
        labelHighscore.setText("(panelHighscore)");

        btnHighscoreBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnHighscoreBack.setText("Tillbaka till huvudmenyn");
        btnHighscoreBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighscoreBackActionPerformed(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jTextPane1.setText("Namn\t\tTyp\t\tDatum\t\tPoäng\n\nPelle\t\tn/a\t\t2014-01-01\t\t10");
        scrPaneHighscore.setViewportView(jTextPane1);

        javax.swing.GroupLayout panelHighscoreLayout = new javax.swing.GroupLayout(panelHighscore);
        panelHighscore.setLayout(panelHighscoreLayout);
        panelHighscoreLayout.setHorizontalGroup(
            panelHighscoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHighscoreLayout.createSequentialGroup()
                .addGroup(panelHighscoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHighscoreLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnHighscoreBack, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHighscoreLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(scrPaneHighscore, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHighscoreLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelHighscore, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(437, 437, 437))
        );
        panelHighscoreLayout.setVerticalGroup(
            panelHighscoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHighscoreLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(labelHighscore, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(scrPaneHighscore, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(btnHighscoreBack)
                .addGap(48, 48, 48))
        );

        getContentPane().add(panelHighscore, "card8");

        labelAddWord.setForeground(new java.awt.Color(255, 255, 255));
        labelAddWord.setText("(panelAddWord)");

        btnAddWordBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnAddWordBack.setText("Tillbaka");
        btnAddWordBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordBackActionPerformed(evt);
            }
        });

        labelCBFrom2.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelCBFrom2.setForeground(new java.awt.Color(255, 255, 255));
        labelCBFrom2.setText("Från:");

        comBoxFrom2.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        comBoxFrom2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Svenska", "Engelska" }));

        labelAddWordFromError.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelAddWordFromError.setForeground(new java.awt.Color(255, 255, 255));
        labelAddWordFromError.setText("<input error field>");

        labelCBTo2.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelCBTo2.setForeground(new java.awt.Color(255, 255, 255));
        labelCBTo2.setText("Till:");

        comBoxTo2.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        comBoxTo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engelska", "Svenska" }));

        labelAddWordToError.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelAddWordToError.setForeground(new java.awt.Color(255, 255, 255));
        labelAddWordToError.setText("<input error field>");

        btnAddWordAdd.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnAddWordAdd.setText("Lägg till glosa");

        btnAddWordClear.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnAddWordClear.setText("Rensa");

        labelSubmitNewLang.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelSubmitNewLang.setForeground(new java.awt.Color(255, 255, 255));
        labelSubmitNewLang.setText("Nytt språk:");

        btnNewLangOK.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnNewLangOK.setText("OK");

        javax.swing.GroupLayout panelAddWordLayout = new javax.swing.GroupLayout(panelAddWord);
        panelAddWord.setLayout(panelAddWordLayout);
        panelAddWordLayout.setHorizontalGroup(
            panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddWordLayout.createSequentialGroup()
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAddWordBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(txtFldAddWordFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAddWordFromError, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddWordLayout.createSequentialGroup()
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddWordLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(txtFldAddWordTo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAddWordLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAddWordLayout.createSequentialGroup()
                                        .addComponent(btnAddWordClear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnAddWordAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comBoxFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCBTo2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCBFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comBoxTo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSubmitNewLang)
                            .addGroup(panelAddWordLayout.createSequentialGroup()
                                .addComponent(txtFldAddWordNewLang, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNewLangOK, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelAddWordToError))))
                .addContainerGap(369, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddWordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(413, 413, 413))
        );
        panelAddWordLayout.setVerticalGroup(
            panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddWordLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(labelAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(labelCBFrom2)
                .addGap(7, 7, 7)
                .addComponent(comBoxFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldAddWordFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAddWordFromError))
                .addGap(67, 67, 67)
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCBTo2)
                    .addComponent(labelSubmitNewLang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comBoxTo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldAddWordNewLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewLangOK, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldAddWordTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAddWordToError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(panelAddWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddWordAdd)
                    .addComponent(btnAddWordClear))
                .addGap(145, 145, 145)
                .addComponent(btnAddWordBack)
                .addGap(53, 53, 53))
        );

        getContentPane().add(panelAddWord, "card9");

        labelListWords.setForeground(new java.awt.Color(255, 255, 255));
        labelListWords.setText("(panelListWords)");

        btnListWordsBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnListWordsBack.setText("Tillbaka");
        btnListWordsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListWordsBackActionPerformed(evt);
            }
        });

        scrPaneListWords.setViewportView(jEditorPane1);

        labelCBFrom3.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelCBFrom3.setForeground(new java.awt.Color(255, 255, 255));
        labelCBFrom3.setText("Från:");

        comBoxFrom3.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        comBoxFrom3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Svenska", "Engelska" }));

        labelCBTo3.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        labelCBTo3.setForeground(new java.awt.Color(255, 255, 255));
        labelCBTo3.setText("Till:");

        comBoxTo3.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        comBoxTo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Engelska", "Svenska" }));

        btnListWordsSave.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnListWordsSave.setText("Spara ändringar");

        btnListWordsShow.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnListWordsShow.setText("Visa lista");

        javax.swing.GroupLayout panelListWordsLayout = new javax.swing.GroupLayout(panelListWords);
        panelListWords.setLayout(panelListWordsLayout);
        panelListWordsLayout.setHorizontalGroup(
            panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListWordsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelListWordsLayout.createSequentialGroup()
                        .addComponent(btnListWordsBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(392, 392, 392))
                    .addGroup(panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrPaneListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelListWordsLayout.createSequentialGroup()
                            .addComponent(labelCBFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comBoxFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(labelCBTo3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comBoxTo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(btnListWordsShow)))
                    .addComponent(btnListWordsSave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        panelListWordsLayout.setVerticalGroup(
            panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListWordsLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(labelListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelListWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCBFrom3)
                    .addComponent(comBoxFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCBTo3)
                    .addComponent(comBoxTo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListWordsShow))
                .addGap(18, 18, 18)
                .addComponent(scrPaneListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnListWordsSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnListWordsBack)
                .addGap(64, 64, 64))
        );

        getContentPane().add(panelListWords, "card10");

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void displaySplashScreen() 
    {
        JWindow window = new JWindow();
        ImageIcon splashIcon = new ImageIcon("images/splash2.png");
        window.getContentPane().add(new JLabel("", splashIcon, SwingConstants.CENTER));
        int splashWidth = splashIcon.getIconWidth();
        int splashHeight = splashIcon.getIconHeight();        
        window.setBounds(screenSize.width / 2 - (splashWidth / 2), screenSize.height / 2 - (splashHeight / 2), splashWidth, splashHeight);
        window.setVisible(true);
               
        // delay
        try 
        {            
            Thread.sleep(splashDelayInSeconds * 1000);
        } 
        catch (InterruptedException e) 
        {            
        }
        window.setVisible(false);
        window.dispose();
    }    
    
    private void createGroupSelectOrType()
    {
        groupSelectOrType = new ButtonGroup();
        groupSelectOrType.add(radBtnSelectChoices);
        groupSelectOrType.add(radBtnTypeWord);
        radBtnTypeWord.setSelected(true);  
    }
    
    public void enableAnswerButton()
    {
        btnNext.setEnabled(true);
    }    
    
    public void disableAnswerButton()
    {
        btnNext.setEnabled(false);
    }
    
    /**
     * Add a listener for the new game button
     * @param listener listener to add
     */
    public void initiateAddListener(ActionListener listener) 
    {
        btnStartGame.addActionListener(listener); 
    }
    
    /**
     * Add a listener for the next (answer) button
     * @param listener listener to add
     */    
    public void nextAddListener(ActionListener listener) 
    {        
        btnNext.addActionListener(listener); 
    }
    
    /**
     * L8
     * Add a listener for end game that will ask for user
     * @param listener listener to add
     */
    public void addEndGameListener(ActionListener listener) 
    {        
        btnEndGame.addActionListener(listener);
    }
    
    /**
     * L8 
     * Gets the user name to add result for
     * @return The user name entered
     */
    public String getUser() {
        String input; 
        input = JOptionPane.showInputDialog("Skriv in ditt namn:");
        return input;
    }
    
    /**
     * Add a listener for the confirm choice button button
     * @param listener listener to add
     */    
    public void confirmChoiceAddListener(ActionListener listener) 
    {        
        btnConfirmLangDiff.addActionListener(listener); 
    }
    
    public void setNewGlossary(String word) 
    {        
        labelWordToTranslate.setText(word);        
    }
    
    public void setGlossaryNumber(int no) 
    {
        String text;
        text = Integer.toString(no);        
        labelWordNo.setText(text + ". "); 
    }
    
    public String getAnswer() 
    {
        String answer = "";        
        answer = txtFldAnswer.getText();
        return answer;
    }
    
    public void setErrorText(String errorMessage) 
    {        
        labelFeedback.setOpaque(true);        
        labelFeedback.setForeground(Color.red); 
        labelFeedback.setText(errorMessage);
                 
        // test
        scrPaneFeedback1.setVisible(true);
        scrPaneFeedback2.setVisible(true);
        
        System.out.println(errorMessage);
    }
    
    public void setCorrectText(String message) 
    {
        labelFeedback.setOpaque(true);
        labelFeedback.setForeground(Color.blue); 
        labelFeedback.setText(message);   
                
        // test
        scrPaneFeedback1.setVisible(true);
        scrPaneFeedback2.setVisible(true);
        
        System.out.println(message);       
    }
    
    public void setEmptyAnswer() 
    {        
        txtFldAnswer.setText("");        
    }
     
    public void setEndText(int total, int correct) 
    {        
        labelEndGame.setText("Du hade " + correct + " rätt av " + total + ".");
    }
    
    /**
     * Checks if user want to write the words him/herself or if the user want to
     * select from a list of words
     * @return true if user want to write own word, else false
     */
    public Boolean isWriteWordSelected() 
    {
        Boolean writeOwnWord;
        if (radBtnTypeWord.isSelected()) 
        {
            writeOwnWord = true;
        }
        else 
        {
            writeOwnWord = false;
        }
        return writeOwnWord;
    }
    
    /** 
     * Writes three alternatives in text field
     * @param wordAlternatives An arrayList with the alternatives
     */
    public void setWordAlternatives(ArrayList<String> wordAlternatives) 
    {
        String tmpString;
        tmpString = "";
        for (int i = 0; i < wordAlternatives.size(); i++) 
        {
             tmpString = tmpString + ";" + wordAlternatives.get(i);
        }
        txtFldAnswer.setText(tmpString);
    }
    
    public void setEmptyEndText()
    {
        labelEndGame.setText("");
    }
    
    public void setEmptyFeedbackText()
    {
        labelFeedback.setText("");
        labelFeedback.setOpaque(false);
                
        // test
        scrPaneFeedback1.setVisible(false);
        scrPaneFeedback2.setVisible(false);
    }   
    
    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        
        panelMainMenu.setVisible(false);
        panelLangDiffSelect.setVisible(true);        
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void comBoxFrom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxFrom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxFrom1ActionPerformed

    private void radBtnSelectChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnSelectChoicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnSelectChoicesActionPerformed

    private void btnConfirmLangDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmLangDiffActionPerformed
        
        panelLangDiffSelect.setVisible(false);
        panelPreGame.setVisible(true);        
    }//GEN-LAST:event_btnConfirmLangDiffActionPerformed

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        
        panelPreGame.setVisible(false);
        panelGame.setVisible(true);        
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void labelSettingsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSettingsIconMouseClicked
        
        panelMainMenu.setVisible(false);
        panelSettings.setVisible(true);        
    }//GEN-LAST:event_labelSettingsIconMouseClicked

    private void btnSettingsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsBackActionPerformed
        
        panelSettings.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnSettingsBackActionPerformed

    private void labelHelpIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHelpIconMouseClicked
        
        panelMainMenu.setVisible(false);
        panelHelp.setVisible(true);         
    }//GEN-LAST:event_labelHelpIconMouseClicked

    private void btnHelpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpBackActionPerformed
        
        panelHelp.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnHelpBackActionPerformed

    private void btnHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighScoreActionPerformed
        
        panelMainMenu.setVisible(false);
        panelHighscore.setVisible(true); 
    }//GEN-LAST:event_btnHighScoreActionPerformed

    private void btnAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordActionPerformed
        
        panelMainMenu.setVisible(false);
        panelAddWord.setVisible(true);  
    }//GEN-LAST:event_btnAddWordActionPerformed

    private void btnListWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListWordsActionPerformed
        
        panelMainMenu.setVisible(false);
        panelListWords.setVisible(true);  
    }//GEN-LAST:event_btnListWordsActionPerformed

    private void btnHighscoreBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighscoreBackActionPerformed
        
        panelHighscore.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnHighscoreBackActionPerformed

    private void btnAddWordBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordBackActionPerformed
        
        panelAddWord.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnAddWordBackActionPerformed

    private void btnListWordsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListWordsBackActionPerformed
        
        panelListWords.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnListWordsBackActionPerformed

    private void btnLangDiffSelectBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLangDiffSelectBackActionPerformed
        
        panelLangDiffSelect.setVisible(false);
        panelMainMenu.setVisible(true); 
    }//GEN-LAST:event_btnLangDiffSelectBackActionPerformed

    private void btnEndGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndGameActionPerformed

        //L8 removed this String input = JOptionPane.showInputDialog("Skriv in ditt namn:");
        
        // TODO add end game handling code here (for saving score, user name ?)
        panelGame.setVisible(false);
        panelHighscore.setVisible(true); 
    }//GEN-LAST:event_btnEndGameActionPerformed

    private void btnPreGameBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreGameBackActionPerformed
               
        panelPreGame.setVisible(false);
        panelLangDiffSelect.setVisible(true); 
    }//GEN-LAST:event_btnPreGameBackActionPerformed

    private void chBoxThreeChoicesYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBoxThreeChoicesYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chBoxThreeChoicesYesActionPerformed

    private void txtFldAnswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFldAnswerFocusGained
                        
        labelFeedback.setOpaque(false);
        labelFeedback.setText("");
                
        // test
        scrPaneFeedback1.setVisible(false);
        scrPaneFeedback2.setVisible(false);
    }//GEN-LAST:event_txtFldAnswerFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWord;
    private javax.swing.JButton btnAddWordAdd;
    private javax.swing.JButton btnAddWordBack;
    private javax.swing.JButton btnAddWordClear;
    private javax.swing.JButton btnConfirmLangDiff;
    private javax.swing.JButton btnEndGame;
    private javax.swing.JButton btnHelpBack;
    private javax.swing.JButton btnHighScore;
    private javax.swing.JButton btnHighscoreBack;
    private javax.swing.JButton btnLangDiffSelectBack;
    private javax.swing.JButton btnListWords;
    private javax.swing.JButton btnListWordsBack;
    private javax.swing.JButton btnListWordsSave;
    private javax.swing.JButton btnListWordsShow;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnNewLangOK;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPreGameBack;
    private javax.swing.JButton btnSettingsBack;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JCheckBox chBoxThreeChoicesYes;
    private javax.swing.JComboBox comBoxDiff;
    private javax.swing.JComboBox comBoxFrom1;
    private javax.swing.JComboBox comBoxFrom2;
    private javax.swing.JComboBox comBoxFrom3;
    private javax.swing.JComboBox comBoxThreeWords;
    private javax.swing.JComboBox comBoxTo1;
    private javax.swing.JComboBox comBoxTo2;
    private javax.swing.JComboBox comBoxTo3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelAddWord;
    private javax.swing.JLabel labelAddWordFromError;
    private javax.swing.JLabel labelAddWordToError;
    private javax.swing.JLabel labelCBDiff;
    private javax.swing.JLabel labelCBFrom1;
    private javax.swing.JLabel labelCBFrom2;
    private javax.swing.JLabel labelCBFrom3;
    private javax.swing.JLabel labelCBThreeWords;
    private javax.swing.JLabel labelCBTo1;
    private javax.swing.JLabel labelCBTo2;
    private javax.swing.JLabel labelCBTo3;
    private javax.swing.JLabel labelChBThreeChoices;
    private javax.swing.JLabel labelEndGame;
    private javax.swing.JTextArea labelFeedback;
    private javax.swing.JLabel labelGame;
    private javax.swing.JLabel labelHelp;
    private javax.swing.JLabel labelHelpIcon;
    private javax.swing.JLabel labelHighscore;
    private javax.swing.JLabel labelLangDiffSelect;
    private javax.swing.JLabel labelListWords;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPreGame;
    private javax.swing.JLabel labelPreGame1;
    private javax.swing.JLabel labelPreGame2;
    private javax.swing.JLabel labelPreGame3;
    private javax.swing.JLabel labelPreGame4;
    private javax.swing.JLabel labelPreGame5;
    private javax.swing.JLabel labelPreGame6;
    private javax.swing.JLabel labelPreGameDiff;
    private javax.swing.JLabel labelPreGameFrom;
    private javax.swing.JLabel labelPreGameSelectType;
    private javax.swing.JLabel labelPreGameTo;
    private javax.swing.JLabel labelRBSelectType;
    private javax.swing.JLabel labelSettings;
    private javax.swing.JLabel labelSettingsIcon;
    private javax.swing.JLabel labelSubmitNewLang;
    private javax.swing.JLabel labelWordNo;
    private javax.swing.JLabel labelWordToTranslate;
    private javax.swing.JPanel panelAddWord;
    private javax.swing.JPanel panelGame;
    private javax.swing.JPanel panelGameTest;
    private javax.swing.JPanel panelGameTest2;
    private javax.swing.JPanel panelHelp;
    private javax.swing.JPanel panelHighscore;
    private javax.swing.JPanel panelLangDiffSelect;
    private javax.swing.JPanel panelListWords;
    private javax.swing.JPanel panelMainMenu;
    private javax.swing.JPanel panelPreGame;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JRadioButton radBtnSelectChoices;
    private javax.swing.JRadioButton radBtnTypeWord;
    private javax.swing.JScrollPane scrPaneFeedback1;
    private javax.swing.JScrollPane scrPaneFeedback2;
    private javax.swing.JScrollPane scrPaneHighscore;
    private javax.swing.JScrollPane scrPaneListWords;
    private javax.swing.JTextField txtFldAddWordFrom;
    private javax.swing.JTextField txtFldAddWordNewLang;
    private javax.swing.JTextField txtFldAddWordTo;
    private javax.swing.JTextField txtFldAnswer;
    // End of variables declaration//GEN-END:variables
}
